### ISSUE TITLE
Improve volunteer onboarding docs

### ISSUE THREAD

**Issue by antoinepetty** [srobo/ops-manual#10]
https://github.com/srobo/ops-manual/wiki/Volunteer-Management#becoming-a-volunteer

Marketing team have a plan for recruitment so will update this section with more detail

**Comment by antoinepetty** [comment]
Maybe this should be moved to the runbook?

**Comment by antoinepetty** [comment]
https://studentrobotics.org/runbook/volunteering/

**Comment by Scarzy** [comment]
Yes, applies more to the runbook than the ops-manual
