### ISSUE TITLE
Discussion: home of volunteer offboarding docs

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/ops-manual#21]
I created https://github.com/srobo/runbook/pull/132 a while back to have a place to link to the spreadsheet of third party services the Infrastructure Team maintain for continuity of access. However it's been pointed out that the ops manual includes a similar page, which might be a better home for that link yet is essentially out of the control of the volunteer teams.

One option here would be to have the ops manual link to the sheet and have the Infrastructure docs in the runook also link to it, however I do wonder if there are going to be other team-specific off-boarding things that will need adding. Obviously we could keep going with the ops-manual even for those, however the cadence at which it is updated is considerably slower than teams own documentation, so that may not be ideal.

Another option would be to move most or all of the off-boarding docs into the runbook. (except perhaps for the trustees section?)

There is a third option of keeping both, with the ops-manual linking to the runbook, however it's not clear to me how that would account for things like the services sheet which are owned by one team but essentially affect off boarding of all volunteers.

**Comment by PeterJCLaw** [comment]
cc @sedders123

**Comment by Scarzy** [comment]
Not applicable to ops-manual.

On-boarding is a team level task, off boarding should equally be so, therefore the runbook is a better home for this. The ops-manual only covers details about the registers and how volunteers, members, and trustees relate.

**Comment by PeterJCLaw** [comment]
Hrm, I've just realised that there's some ambiguity here. The page that @seders123 linked to from my PR was https://github.com/srobo/ops-manual/wiki/Volunteer-Management, which is _sort of_ part of the ops manual, though possibly now out of date? Certainly what's there covers a lot more operational detail than just how to register new volunteers. It was that page which I was mostly referring to here, though I'd completely failed to realise that it wasn't part of the published ops manual.

@Scarzy had you seen that page/realised that that was the content being referenced here?

For clarity: I don't disagree with the expectation that the ops manual focus only on the basic needs of registering volunteers, though perhaps the wiki pages from this repo just need reviewing?

**Comment by PeterJCLaw** [comment]
@Scarzy just checking you saw the clarification here? (feel free to re-close if the resolution is the same)

**Comment by Scarzy** [comment]
Resolution from before still applies.

There was already a note on the home page of the wiki stating that it is superseded by the live ops-manual. I've extended that note to make it clear that the ops-manual wiki now largely exists for historical reference
