### ISSUE TITLE
Review recorded volunteer details

### ISSUE THREAD

**Issue by antoinepetty** [srobo/ops-manual#30]
This section states that we collect names, mobile numbers, and general locations of every volunteer.
https://opsmanual.studentrobotics.org/about-the-charity/volunteers

I don't recall this being the case for myself or the volunteers we have been onboarding. Is this still the case? We probably *should* be keeping these details even if we aren't at the moment.

**Comment by dianedowling** [comment]
We don't keep these details so I have removed from ops manual.
